[김성수] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/29-westagram-backend-1-team pull request #13
Opened 2022-01-14 07:18 UTC by shawn365

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
users/views안에 post 생성 완료
		 
## 수정 사항들 자세한 내용
- users/views get 삭제 완료
- try except으로 keyerror 시 메세지 반환 가능
- 자주쓰는 email, password 변수선언 
- urls.py path 추가 ("/signup")
- models.py password 최대길이 수정
- user_data['name'] 값이 입력이 안된경우 에러 메세지 추가
- branch 새로 생성 (seongsu/signup)
## 기타 질문 및 특이 사항
- 전에 seongsu/models branch에서 mission3 진행하던거 push 했었는데 취소방법을 모르겠습니다
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 07:30 UTC, lordmyshepherd requested changes

2022-01-14 07:30 UTC, lordmyshepherd commented on students/seongsu/westagram/users/views.py
> +
```suggestion
```

2022-01-14 07:30 UTC, lordmyshepherd commented on students/seongsu/westagram/users/views.py
> +            elif not re.fullmatch(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+', email):
```suggestion
     REGEX_EMAIL = r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+'
     REGEX_PASSWORD = r'..'
     
            elif not re.fullmatch(REGEX_EMAIL, email):
```

2022-01-14 07:42 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
> +
수정완료

2022-01-14 07:42 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
> +            elif not re.fullmatch(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+', email):
수정완료

2022-01-14 08:14 UTC, lordmyshepherd requested changes

2022-01-14 08:14 UTC, lordmyshepherd commented on students/seongsu/westagram/users/views.py
> +            regex_password = r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
상수는 변수명을 대문자로 만들어주세요~

2022-01-14 08:27 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
> +            regex_password = r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
수정완료

2022-01-17 01:33 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-17 01:33 UTC, merged