[김준영] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/29-westagram-backend-1-team pull request #14
Opened 2022-01-14 07:36 UTC by aerialslash0422

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 View 작성
		 
## 수정 사항들 자세한 내용
- 클라이언트 호출을 받아서 로그인 뷰인 SignInView를 호출할 수 있도록 urls.py 작성
- 클라이언트는 이메일과 패스워드를 입력
- 이메일, 패스워드 미입력시 KeyError반환
- filter 메소드를 이용해 이메일,패스워드 틀릴 시 에러메세지 반환 
- 성공시 로그인 성공 메세지, 200 OK 반환
- 정규식 두번째 리팩토링(모든 문자가 아니라 알파벳 대소문자만 해당되게, 특수문자는 Shift 1~8만)
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 12:35 UTC, jxngbxxm commented on students/junyoung/westagram/users/views.py
>              return JsonResponse({"message" : f"KEY_ERROR : ENTER_YOUR_{e.args[0].upper()}"}, status = 400)
로그인 정보에서 입력값 공백에 대한 에러 처리를 이렇게도 할 수 있구나 싶었네요. 좋은 방법인 것 같습니다 준영님! 👍 👍

2022-01-17 02:55 UTC, shawn365 commented on students/junyoung/westagram/users/views.py
>              return JsonResponse({"message" : f"KEY_ERROR : ENTER_YOUR_{e.args[0].upper()}"}, status = 400)
Email 이랑 비밀번호가 매칭이 안되도 유저가 보낸 비밀번호가 데이터 베이스에 들어있기만 하면 로그인이 될거 같은데요 확인 부탁드립니다

2022-01-17 03:49 UTC, aerialslash0422 commented on students/junyoung/westagram/users/views.py
>              return JsonResponse({"message" : f"KEY_ERROR : ENTER_YOUR_{e.args[0].upper()}"}, status = 400)
성수님 의견 반영했습니다!
확인해보니 user id의 email은 일치해도 password가 다른 id것이면 로그인 완료 메시지가 떠서 
마지막 elif문에 email = email 조건을 추가하는 것으로 수정 완료했습니다.

2022-01-17 04:34 UTC, shawn365 commented on students/junyoung/westagram/users/views.py
>              return JsonResponse({"message" : f"KEY_ERROR : ENTER_YOUR_{e.args[0].upper()}"}, status = 400)
👍 👍

2022-01-17 04:57 UTC, lordmyshepherd requested changes

2022-01-17 04:57 UTC, lordmyshepherd commented on students/junyoung/westagram/users/views.py
> +                return JsonResponse({"message" : "INVALID_PASSWORD"}, status = 401)
line 51,52 코드와 54, 55 코드가 둘 다 필요한가요?
```suggestion
            if not User.objects.filter(email = email).exists():
                return JsonResponse({"message" : "INVALID_USER"}, status = 401)
        
            elif not User.objects.filter(email = email, password = password).exists():
                return JsonResponse({"message" : "INVALID_PASSWORD"}, status = 401)
```

2022-01-17 04:57 UTC, lordmyshepherd commented on students/junyoung/westagram/users/views.py
>              return JsonResponse({"message" : f"KEY_ERROR : ENTER_YOUR_{e.args[0].upper()}"}, status = 400)
피어리뷰 정말 잘 하고 계시네요!! ❤️

2022-01-17 05:13 UTC, aerialslash0422 commented on students/junyoung/westagram/users/views.py
> +                return JsonResponse({"message" : "INVALID_PASSWORD"}, status = 401)
Assignment에 계정,비밀번호 에러코드가 전부 invalid_user로 동일한 것을 못봤습니다.
54~55는 계정은 일치하는데 비밀번호가 틀리면 invalid_password를 출력하는 코드입니다.
과제에 맞게 수정하겠습니다.

2022-01-17 05:20 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-17 05:20 UTC, merged