[김성수] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/29-westagram-backend-1-team pull request #20
Opened 2022-01-17 08:07 UTC by shawn365

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- JWT 발급
		 
## 수정 사항들 자세한 내용
- JWT 발급
- pip freeze로 requirements.txt 업데이트
- import에 jwt 추가

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-17 08:25 UTC, jxngbxxm commented on students/seongsu/westagram/users/views.py
>              user = User.objects.get(email = email)
```suggestion
            email    = user_data['email']
            password = user_data['password']
            user     = User.objects.get(email = email)
```
convention만 조금 맞춰주시면 완벽할 것 같습니다 성수님!

2022-01-18 01:13 UTC, jxngbxxm commented on students/seongsu/westagram/users/views.py
> +            access_token = jwt.encode({'id' : user.id}, user.password, algorithm = 'HS256')
인증 & 인가 세션에서 호준님께서 해주신 말씀처럼 토큰 또한 어떠한 이유로 탈취(해킹)가 된다면 로그인이 필요한 모든 액션에 사용될 수 있기 때문에  algorithm 부분 어떤 알고리즘으로 토큰을 만들었는지 모르게 따로 my_settings에 처리하는 것이(실제 서비스한다고 가정했을 때) 보안면에서 더 안전한 코드가 될 것 같습니다~~ user.password 부분도 비슷한 이유로 개인정보보다는 저희가 초기세팅 과정에서 .gitignore로 처리하였던 django secret_key를 활용해보시면 어떨까요?

2022-01-18 01:15 UTC, jxngbxxm commented on students/seongsu/westagram/users/views.py
> +            access_token = jwt.encode({'id' : user.id}, user.password, algorithm = 'HS256')
인증 & 인가 세션에서 호준님께서 해주신 말씀처럼 토큰 또한 어떠한 이유로 탈취(해킹)가 된다면 로그인이 필요한 모든 액션에 사용될 수 있기 때문에  algorithm 부분 어떤 알고리즘으로 토큰을 만들었는지 모르게 따로 my_settings에 처리하는 것이(실제 서비스한다고 가정했을 때) 보안면에서 더 안전한 코드가 될 것 같습니다~~ user.password 부분도 비슷한 이유로 개인정보보다는 저희가 초기세팅 과정에서 .gitignore로 처리하였던 django secret_key를 활용해보시면 어떨까요?

2022-01-18 02:06 UTC, jxngbxxm commented on students/seongsu/westagram/users/views.py
> +            access_token = jwt.encode({'id' : user.id}, user.password, algorithm = 'HS256')
61번줄에서 인증 & 인가 세션에서 호준님께서 해주신 말씀처럼 토큰 또한 어떠한 이유로 탈취(해킹)가 된다면 로그인이 필요한 모든 액션에 사용될 수 있기 때문에 , signature 부분을 암호화할때 `algorithm`은 어떤 알고리즘으로 만들었는지 모르게 따로 `my_settings`에 처리하는 것이(실제 서비스한다고 가정했을 때) 보안면에서 더 안전한 코드가 될 것 같습니다~~ 55번줄의 `user.password` 부분도 비슷한 이유로 비밀번호 같은 개인정보보다는 저희가 초기세팅 과정에서 외부나 깃에 노출되지 않도록 하기위해 `.gitignore`로 처리하였던 django secret_key를 활용해보시면 어떨까요?

2022-01-18 04:10 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
>              user = User.objects.get(email = email)
수정했습니다~

2022-01-18 04:11 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
>              return JsonResponse({"message" : "KEY_ERROR: " + str(e).replace("'", '')}, status = 400)
수정했습니다

2022-01-18 04:23 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
> +            access_token = jwt.encode({'id' : user.id}, user.password, algorithm = 'HS256')
확실히 그렇게 하는게 좋아보이네요 수정 했습니다~~
근데 django secret_key는 유저 한명의 비밀번호보다 더 중요한거 아닌가요??

2022-01-18 05:19 UTC, lordmyshepherd requested changes

2022-01-18 05:19 UTC, lordmyshepherd commented on students/seongsu/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')) == False:
파이썬 PEP 8 프로그래밍 권고에는 비교문 관련해서 어떤 형식을 사용하라고 안내되어 있습니다.

- True/False를 비교할 때는 if문에 변수만 사용하도록 한다.
- 동등성(단순히 값만 비교하는 경우)을 검증할 때는 == 혹은 != 같은 연산자를 사용하도록 한다.
- 동일성(객체의 고유 메모리 주소로 비교하는 경우)을 검증할 때는 is나 is not을 사용한다.

즉 아래의 경우는 True/False만을 비교하기 때문에 == False는 붙일 필요가 없습니다.
```suggestion
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
```

2022-01-18 05:26 UTC, shawn365 commented on students/seongsu/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')) == False:
false 대신 not 붙여서 수정 했습니다

2022-01-18 05:49 UTC, lordmyshepherd approved these changes

2022-01-18 05:49 UTC, merged