[김준영] Mission 2 : 모델링
wecode-bootcamp-korea/29-westagram-backend-1-team pull request #9
Opened 2022-01-13 07:00 UTC by aerialslash0422

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
회원가입 모델링 작성

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- requirement.txt 수정
- users app 생성
- users/models.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-13 07:05 UTC, lordmyshepherd requested changes

2022-01-13 07:05 UTC, lordmyshepherd commented on students/junyoung/westagram/users/models.py
> +    phone_number = models.CharField(max_length=100)
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2022-01-13 07:05 UTC, lordmyshepherd commented on students/junyoung/westagram/users/models.py
> +    password     = models.CharField(max_lenght=100)
나중에 해시(암호화)된 비밀번호가 저장될 수 있도록 길이를 고려해서 넉넉하게 200 이상으로 설정해주세요.

2022-01-13 07:06 UTC, bigfanoftim requested changes

2022-01-13 07:06 UTC, bigfanoftim commented on students/junyoung/westagram/users/models.py
> +    password     = models.CharField(max_lenght=100)
이후에 암호화된 password를 저장하기 위해 max_length를 넉넉하게 잡아주세요!
```suggestion
    password     = models.CharField(max_lenght=200)
```

2022-01-14 05:33 UTC, lordmyshepherd requested changes

2022-01-14 05:33 UTC, lordmyshepherd commented on students/junyoung/westagram/users/views.py
> +class SignUpView(View):
Mission 2: 모델링 기능인데 회원가입 관련된 코드가 들어있네요?!
모델링 관련된 코드만 남기고 지워주세요~!

2022-01-14 06:34 UTC, closed without merging